# k-means clustering


In [1]:
import cv2
import numpy as np

In [2]:
img=cv2.imread("C:/Users/SN127/Desktop/messi.jpg")

In [3]:
img

array([[[221, 194, 180],
        [220, 193, 179],
        [219, 193, 177],
        ...,
        [215, 212, 198],
        [210, 208, 198],
        [208, 207, 197]],

       [[217, 190, 176],
        [216, 190, 174],
        [215, 189, 173],
        ...,
        [207, 203, 192],
        [201, 200, 190],
        [198, 199, 189]],

       [[216, 191, 175],
        [215, 191, 173],
        [214, 188, 171],
        ...,
        [201, 199, 188],
        [195, 196, 186],
        [192, 195, 186]],

       ...,

       [[249, 238, 178],
        [248, 237, 175],
        [249, 236, 174],
        ...,
        [253, 254, 252],
        [253, 254, 252],
        [253, 254, 252]],

       [[249, 238, 178],
        [249, 238, 176],
        [250, 237, 175],
        ...,
        [253, 254, 252],
        [253, 254, 252],
        [253, 254, 252]],

       [[251, 240, 180],
        [250, 239, 177],
        [251, 238, 176],
        ...,
        [253, 254, 252],
        [253, 254, 252],
        [253, 254, 252]]

# RGB CONVERTION

In [6]:
imgrgb=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)

In [7]:
vec = imgrgb.reshape((-2,4))
vec

array([[180, 194, 221, 179],
       [193, 220, 177, 193],
       [219, 177, 194, 220],
       ...,
       [252, 254, 253, 252],
       [254, 253, 252, 254],
       [253, 252, 254, 253]], dtype=uint8)

In [8]:
vec = np.float32(vec)
vec

array([[180., 194., 221., 179.],
       [193., 220., 177., 193.],
       [219., 177., 194., 220.],
       ...,
       [252., 254., 253., 252.],
       [254., 253., 252., 254.],
       [253., 252., 254., 253.]], dtype=float32)

# iteration termination criteria

In [9]:
criteria = (cv2.TERM_CRITERIA_EPS+cv2.TERM_CRITERIA_MAX_ITER,100,1)

# cluster condition

In [19]:
k = 3
attempts = 100

In [20]:
compactness,label,center = cv2.kmeans(vec,k,None,criteria,attempts,cv2.KMEANS_PP_CENTERS)
center

array([[137.09572 , 141.47806 , 141.83098 , 136.91125 ],
       [ 43.59853 ,  43.94036 ,  44.41616 ,  43.495247],
       [217.88573 , 214.60425 , 214.56837 , 217.99905 ]], dtype=float32)

In [21]:
center =np.uint8(center)
center



array([[137, 141, 141, 136],
       [ 43,  43,  44,  43],
       [217, 214, 214, 217]], dtype=uint8)

In [25]:
res = center[label.flatten()]
res_img=res.reshape((imgrgb.shape))
res_img

array([[[217, 214, 214],
        [217, 217, 214],
        [214, 217, 217],
        ...,
        [217, 217, 214],
        [214, 217, 217],
        [214, 214, 217]],

       [[217, 214, 214],
        [217, 217, 214],
        [214, 217, 217],
        ...,
        [217, 217, 214],
        [214, 217, 217],
        [214, 214, 217]],

       [[217, 214, 214],
        [217, 217, 214],
        [214, 217, 217],
        ...,
        [217, 217, 214],
        [214, 217, 217],
        [214, 214, 217]],

       ...,

       [[217, 214, 214],
        [217, 217, 214],
        [214, 217, 217],
        ...,
        [217, 217, 214],
        [214, 217, 217],
        [214, 214, 217]],

       [[217, 214, 214],
        [217, 217, 214],
        [214, 217, 217],
        ...,
        [217, 217, 214],
        [214, 217, 217],
        [214, 214, 217]],

       [[217, 214, 214],
        [217, 217, 214],
        [214, 217, 217],
        ...,
        [217, 217, 214],
        [214, 217, 217],
        [214, 214, 217]]

In [27]:
cv2.imshow("img",img)
cv2.imshow("segmented",res_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [32]:
img=cv2.imread("C:/Users/SN127/Desktop/messi.jpg")
segmented_image=cv2.pyrMeanShiftFiltering(img,40,40)
cv2.imshow("img",img)
cv2.imshow("segmented",segmented_image)
cv2.waitKey(0)
cv2.destroyAllWindows()